=== ThallingerLab/LDA2/dtds/WholeSet.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT abs-settings-whole (exp-settings,class-settings)>

<!ELEMENT exp-settings (exp-setting*)>
<!ELEMENT exp-setting (setting*)>
<!ATTLIST exp-setting
		name	CDATA #REQUIRED>

<!ELEMENT class-settings (class-setting*)>
<!ELEMENT class-setting (setting*,es-setting*,is-setting*,exp-stand-settings?)>
<!ATTLIST class-setting
		lipid-class	CDATA #REQUIRED>

<!ELEMENT es-setting (setting*)>
<!ATTLIST es-setting
		name	CDATA #REQUIRED>

<!ELEMENT is-setting (setting*)>
<!ATTLIST is-setting
		name	CDATA #REQUIRED>		
		
<!ELEMENT exp-stand-settings (exp-stand-setting*)>

<!ELEMENT exp-stand-setting (setting?,es-setting*,is-setting*)>
<!ATTLIST exp-stand-setting
		name	CDATA #REQUIRED>

<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
		name		CDATA #REQUIRED
		magnitude	CDATA #REQUIRED
		value		CDATA #REQUIRED>

=== ThallingerLab/LDA2/examples/phospholipids.wqs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE abs-settings-whole SYSTEM "WholeSet.dtd">
<abs-settings-whole><exp-settings><exp-setting name="20100126_PLpos-42"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="3104"/><setting magnitude="m" name="neutral-lipid-concentration" value="7826"/></exp-setting><exp-setting name="20100126_PLpos-39"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="528"/><setting magnitude="m" name="neutral-lipid-concentration" value="774.09"/></exp-setting><exp-setting name="20100126_PLpos-41"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="3050"/><setting magnitude="m" name="neutral-lipid-concentration" value="7905"/></exp-setting><exp-setting name="20100126_PLpos-38"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="340.22"/><setting magnitude="m" name="neutral-lipid-concentration" value="360.45"/></exp-setting><exp-setting name="20100126_PLpos-40"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="2918"/><setting magnitude="m" name="neutral-lipid-concentration" value="7951"/></exp-setting><exp-setting name="20100126_PLpos-37"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="430.22"/><setting magnitude="m" name="neutral-lipid-concentration" value="426.36"/></exp-setting><exp-setting name="20100126_PLpos-36"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="209.8"/><setting magnitude="m" name="neutral-lipid-concentration" value="1058.64"/></exp-setting><exp-setting name="20100126_PLpos-35"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="335.8"/><setting magnitude="m" name="neutral-lipid-concentration" value="1517.73"/></exp-setting><exp-setting name="20100126_PLpos-34"><setting magnitude="m" name="probe-volume" value="2"/><setting magnitude="µ" name="end-volume" value="200"/><setting magnitude="m" name="protein-concentration" value="178.8"/><setting magnitude="m" name="neutral-lipid-concentration" value="858.64"/></exp-setting></exp-settings><class-settings><class-setting lipid-class="SM"><setting magnitude="" name="all-experiments-same" value="true"/><setting magnitude="" name="all-standards-same" value="true"/><setting magnitude="" name="dilution-factor" value="1"/><es-setting name="general"/><is-setting name="general"><setting magnitude="µ" name="int-volume" value="200"/><setting magnitude="µ" name="int-concentration" value="1"/></is-setting></class-setting><class-setting lipid-class="PE"><setting magnitude="" name="all-experiments-same" value="true"/><setting magnitude="" name="all-standards-same" value="true"/><setting magnitude="" name="dilution-factor" value="1"/><es-setting name="general"/><is-setting name="general"><setting magnitude="µ" name="int-volume" value="200"/><setting magnitude="µ" name="int-concentration" value="1"/></is-setting></class-setting><class-setting lipid-class="PC"><setting magnitude="" name="all-experiments-same" value="true"/><setting magnitude="" name="all-standards-same" value="true"/><setting magnitude="" name="dilution-factor" value="1"/><es-setting name="general"/><is-setting name="general"><setting magnitude="µ" name="int-volume" value="200"/><setting magnitude="µ" name="int-concentration" value="1"/></is-setting></class-setting></class-settings></abs-settings-whole>
